# set_commands is used to load a full NGFW configuration

# snippet folder name
name: skillet_set_command_panos_v81
# label used for menu selection
label: v8.1 Iron-Skillet set commands for NGFW
description: Iron-Skillet baseline configuration for a firewall
dependency:
# type of device configuration
type: template
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet_set
  collection:
    - IronSkillet

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
  - name: NTP_1
    description: Network Time Protocol Server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: Network Time Protocol Server 2
    default: 1.pool.ntp.org
    type_hint: text
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: password
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: ip_address
  - name: SINKHOLE_IPV4
    description: sinkhole address IPv4
    default: 72.5.65.111
    type_hint: ip_address
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text

snippets:
  - name: iron_skillet_panos_full.conf
    file: iron_skillet_panos_full.conf
