# snippet folder name
name: AWS AWS transit gateway palo alto firewall config
# label used for menu selection
label: AWS transit gateway
description: This is the palo alto firewall config for Palo Alto AWS transit gateway architecture
dependency:
# type of device configuration
type: template
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: AWS transit gateway
  collection:
    - AWS transit gateway

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: disabled_entry
    description: Please read the following readme before use it
    default: https://github.com/caibitim/cdw_skillet/tree/dev/template
    type_hint: disabled

  - name: AWS_GW_1_KEY
    description: AWS VPN gateway 1 preshared-key
    default: Z^brHwU^w6Ux2T^9VUN
    help_text: this is the dummy IPSEC pre-shared key value, you have to overide it manually from the template stack on panorama  

  - name: AWS_GW_2_KEY
    description: AWS VPN gateway 2 preshared-key
    default: Z^brHwU^w6Ux2T^9VUN
    help_text: this is the dummy IPSEC pre-shared key value, you have to overide it manually from the template stack on panorama



snippets:
  - name: aws_tgw_firewall.conf
    file: aws_tgw_firewall.conf
